//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ellamey
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Data.Entity.Core.Objects.DataClasses;
    using System.Linq;
    
    public partial class EllameyEntities : DbContext
    {
        public EllameyEntities()
            : base("name=EllameyEntities")
        {
            this.Configuration.LazyLoadingEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Country> Countries { get; set; }
        public DbSet<Grocer> Grocers { get; set; }
        public DbSet<GroceryItem> GroceryItems { get; set; }
        public DbSet<GroceryOrder> GroceryOrders { get; set; }
        public DbSet<GroceryOrderItem> GroceryOrderItems { get; set; }
        public DbSet<OrderStatusGrocer> OrderStatusGrocers { get; set; }
        public DbSet<OrderStatusRestaurateur> OrderStatusRestaurateurs { get; set; }
        public DbSet<PaymentMethod> PaymentMethods { get; set; }
        public DbSet<PaymentStatu> PaymentStatus { get; set; }
        public DbSet<RestaurantOrder> RestaurantOrders { get; set; }
        public DbSet<Restaurateur> Restaurateurs { get; set; }
        public DbSet<Role> Roles { get; set; }
        public DbSet<State> States { get; set; }
        public DbSet<Unit> Units { get; set; }
        public DbSet<Login> Logins { get; set; }
        public DbSet<FoodCategory> FoodCategories { get; set; }
        public DbSet<FoodItem> FoodItems { get; set; }
        public DbSet<FoodSubCategory> FoodSubCategories { get; set; }
        public DbSet<RestaurantOrderItem> RestaurantOrderItems { get; set; }
    
        public virtual int sp_getrestaurants(Nullable<double> lATITUDE, Nullable<double> lONGITUDE, Nullable<double> distance)
        {
            var lATITUDEParameter = lATITUDE.HasValue ?
                new ObjectParameter("LATITUDE", lATITUDE) :
                new ObjectParameter("LATITUDE", typeof(double));
    
            var lONGITUDEParameter = lONGITUDE.HasValue ?
                new ObjectParameter("LONGITUDE", lONGITUDE) :
                new ObjectParameter("LONGITUDE", typeof(double));
    
            var distanceParameter = distance.HasValue ?
                new ObjectParameter("Distance", distance) :
                new ObjectParameter("Distance", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_getrestaurants", lATITUDEParameter, lONGITUDEParameter, distanceParameter);
        }
    
        public virtual int sp_getrestaurants1(Nullable<double> lATITUDE, Nullable<double> lONGITUDE, Nullable<double> distance)
        {
            var lATITUDEParameter = lATITUDE.HasValue ?
                new ObjectParameter("LATITUDE", lATITUDE) :
                new ObjectParameter("LATITUDE", typeof(double));
    
            var lONGITUDEParameter = lONGITUDE.HasValue ?
                new ObjectParameter("LONGITUDE", lONGITUDE) :
                new ObjectParameter("LONGITUDE", typeof(double));
    
            var distanceParameter = distance.HasValue ?
                new ObjectParameter("Distance", distance) :
                new ObjectParameter("Distance", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_getrestaurants1", lATITUDEParameter, lONGITUDEParameter, distanceParameter);
        }
    
        public virtual int sp_getrestaurants2(Nullable<double> lATITUDE, Nullable<double> lONGITUDE, Nullable<double> distance)
        {
            var lATITUDEParameter = lATITUDE.HasValue ?
                new ObjectParameter("LATITUDE", lATITUDE) :
                new ObjectParameter("LATITUDE", typeof(double));
    
            var lONGITUDEParameter = lONGITUDE.HasValue ?
                new ObjectParameter("LONGITUDE", lONGITUDE) :
                new ObjectParameter("LONGITUDE", typeof(double));
    
            var distanceParameter = distance.HasValue ?
                new ObjectParameter("Distance", distance) :
                new ObjectParameter("Distance", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_getrestaurants2", lATITUDEParameter, lONGITUDEParameter, distanceParameter);
        }
    
        public virtual int sp_getgroceryshops(Nullable<double> lATITUDE, Nullable<double> lONGITUDE, Nullable<double> distance)
        {
            var lATITUDEParameter = lATITUDE.HasValue ?
                new ObjectParameter("LATITUDE", lATITUDE) :
                new ObjectParameter("LATITUDE", typeof(double));
    
            var lONGITUDEParameter = lONGITUDE.HasValue ?
                new ObjectParameter("LONGITUDE", lONGITUDE) :
                new ObjectParameter("LONGITUDE", typeof(double));
    
            var distanceParameter = distance.HasValue ?
                new ObjectParameter("Distance", distance) :
                new ObjectParameter("Distance", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_getgroceryshops", lATITUDEParameter, lONGITUDEParameter, distanceParameter);
        }
    
        public virtual int sp_getgroceryshops1(Nullable<double> lATITUDE, Nullable<double> lONGITUDE, Nullable<double> distance)
        {
            var lATITUDEParameter = lATITUDE.HasValue ?
                new ObjectParameter("LATITUDE", lATITUDE) :
                new ObjectParameter("LATITUDE", typeof(double));
    
            var lONGITUDEParameter = lONGITUDE.HasValue ?
                new ObjectParameter("LONGITUDE", lONGITUDE) :
                new ObjectParameter("LONGITUDE", typeof(double));
    
            var distanceParameter = distance.HasValue ?
                new ObjectParameter("Distance", distance) :
                new ObjectParameter("Distance", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_getgroceryshops1", lATITUDEParameter, lONGITUDEParameter, distanceParameter);
        }
    
        public virtual int sp_getrestaurants3(Nullable<double> lATITUDE, Nullable<double> lONGITUDE, Nullable<double> distance)
        {
            var lATITUDEParameter = lATITUDE.HasValue ?
                new ObjectParameter("LATITUDE", lATITUDE) :
                new ObjectParameter("LATITUDE", typeof(double));
    
            var lONGITUDEParameter = lONGITUDE.HasValue ?
                new ObjectParameter("LONGITUDE", lONGITUDE) :
                new ObjectParameter("LONGITUDE", typeof(double));
    
            var distanceParameter = distance.HasValue ?
                new ObjectParameter("Distance", distance) :
                new ObjectParameter("Distance", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_getrestaurants3", lATITUDEParameter, lONGITUDEParameter, distanceParameter);
        }
    
        public virtual ObjectResult<sp_getgroceryshops_Result> sp_getgroceryshops2(Nullable<double> lATITUDE, Nullable<double> lONGITUDE, Nullable<double> distance)
        {
            var lATITUDEParameter = lATITUDE.HasValue ?
                new ObjectParameter("LATITUDE", lATITUDE) :
                new ObjectParameter("LATITUDE", typeof(double));
    
            var lONGITUDEParameter = lONGITUDE.HasValue ?
                new ObjectParameter("LONGITUDE", lONGITUDE) :
                new ObjectParameter("LONGITUDE", typeof(double));
    
            var distanceParameter = distance.HasValue ?
                new ObjectParameter("Distance", distance) :
                new ObjectParameter("Distance", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_getgroceryshops_Result>("sp_getgroceryshops2", lATITUDEParameter, lONGITUDEParameter, distanceParameter);
        }
    
        public virtual ObjectResult<sp_getrestaurants_Result> sp_getrestaurants4(Nullable<double> lATITUDE, Nullable<double> lONGITUDE, Nullable<double> distance)
        {
            var lATITUDEParameter = lATITUDE.HasValue ?
                new ObjectParameter("LATITUDE", lATITUDE) :
                new ObjectParameter("LATITUDE", typeof(double));
    
            var lONGITUDEParameter = lONGITUDE.HasValue ?
                new ObjectParameter("LONGITUDE", lONGITUDE) :
                new ObjectParameter("LONGITUDE", typeof(double));
    
            var distanceParameter = distance.HasValue ?
                new ObjectParameter("Distance", distance) :
                new ObjectParameter("Distance", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_getrestaurants_Result>("sp_getrestaurants4", lATITUDEParameter, lONGITUDEParameter, distanceParameter);
        }
    }
}
