//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ellamey
{
    using System;
    using System.Collections.Generic;
    
    public partial class FoodCategory
    {
        public FoodCategory()
        {
            this.FoodSubCategories = new HashSet<FoodSubCategory>();
        }
    
        public int FoodCategoryId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual ICollection<FoodSubCategory> FoodSubCategories { get; set; }
    }
}
