//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ellamey
{
    using System;
    using System.Collections.Generic;
    
    public partial class FoodItem
    {
        public FoodItem()
        {
            this.RestaurantOrderItems = new HashSet<RestaurantOrderItem>();
        }
    
        public int FoodItemId { get; set; }
        public int RestaurateurId { get; set; }
        public string Name { get; set; }
        public string Price { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<bool> IsOutofstock { get; set; }
        public string PhotoPath { get; set; }
        public Nullable<int> FoodCategoryId { get; set; }
        public Nullable<int> FoodSubCategoryId { get; set; }
    
        public virtual Restaurateur Restaurateur { get; set; }
        public virtual ICollection<RestaurantOrderItem> RestaurantOrderItems { get; set; }
    }
}
