//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ellamey
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroceryOrderItem
    {
        public int GroceryOrderItemsId { get; set; }
        public int GroceryOrderId { get; set; }
        public int Quantity { get; set; }
        public string Price { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public int GroceryItemId { get; set; }
    
        public virtual GroceryItem GroceryItem { get; set; }
        public virtual GroceryOrder GroceryOrder { get; set; }
    }
}
