//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ellamey
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroceryItem
    {
        public GroceryItem()
        {
            this.GroceryOrderItems = new HashSet<GroceryOrderItem>();
        }
    
        public int GroceryItemId { get; set; }
        public int GrocerId { get; set; }
        public string Name { get; set; }
        public string weight { get; set; }
        public int unitid { get; set; }
        public string price { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<bool> IsOutofstock { get; set; }
        public string PhotoPath { get; set; }
    
        public virtual Grocer Grocer { get; set; }
        public virtual Unit Unit { get; set; }
        public virtual ICollection<GroceryOrderItem> GroceryOrderItems { get; set; }
    }
}
