//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ellamey
{
    using System;
    using System.Collections.Generic;
    
    public partial class Login
    {
        public Login()
        {
            this.GroceryOrders = new HashSet<GroceryOrder>();
            this.RestaurantOrders = new HashSet<RestaurantOrder>();
        }
    
        public int LoginId { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
        public bool isToRead { get; set; }
        public int RoleId { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string Name { get; set; }
        public string PhoneNumber { get; set; }
        public Nullable<int> RestaurateurId { get; set; }
        public Nullable<int> GrocerId { get; set; }
        public string PhotoPath { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string postalcode { get; set; }
        public string city { get; set; }
        public Nullable<int> stateid { get; set; }
        public Nullable<int> countryid { get; set; }
    
        public virtual ICollection<GroceryOrder> GroceryOrders { get; set; }
        public virtual Role Role { get; set; }
        public virtual ICollection<RestaurantOrder> RestaurantOrders { get; set; }
    }
}
