//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ellamey
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentStatu
    {
        public PaymentStatu()
        {
            this.GroceryOrders = new HashSet<GroceryOrder>();
            this.RestaurantOrders = new HashSet<RestaurantOrder>();
        }
    
        public int PaymentStatusId { get; set; }
        public string PaymentStatusName { get; set; }
        public string Description { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual ICollection<GroceryOrder> GroceryOrders { get; set; }
        public virtual ICollection<RestaurantOrder> RestaurantOrders { get; set; }
    }
}
