//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ellamey
{
    using System;
    using System.Collections.Generic;
    
    public partial class Restaurateur
    {
        public Restaurateur()
        {
            this.RestaurantOrders = new HashSet<RestaurantOrder>();
            this.FoodItems = new HashSet<FoodItem>();
        }
    
        public int RestaurateurId { get; set; }
        public string Name { get; set; }
        public string city { get; set; }
        public string website { get; set; }
        public string phonenumber { get; set; }
        public string email { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string address1 { get; set; }
        public string address2 { get; set; }
        public int stateid { get; set; }
        public int countryid { get; set; }
        public string gstin { get; set; }
        public string bankaccountname { get; set; }
        public string bankname { get; set; }
        public string ifsccode { get; set; }
        public string accountnumber { get; set; }
        public string postalcode { get; set; }
        public Nullable<double> latitude { get; set; }
        public Nullable<double> longitude { get; set; }
        public string PhotoPath { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual ICollection<RestaurantOrder> RestaurantOrders { get; set; }
        public virtual State State { get; set; }
        public virtual ICollection<FoodItem> FoodItems { get; set; }
    }
}
